on:
  push:
    branches:
    - main
jobs:
  trigger-vulrep-scan:
    runs-on: ubuntu-latest
    name: Trigger a Vulrep scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Vulrep GitHub Action
        uses: vulteria/vulrep-cli@v0.3.0
        with:
          project_code: 20nuZRTEOF
          token: ${{ secrets.VULREP_TOKEN }}
        
