on:
  push:
    branches:
    - main
jobs:
  trigger-vulrep-scan:
    runs-on: ubuntu-latest
    name: Trigger a Vulrep scan
    steps:
      - uses: actions/checkout@v3
      - name: Vulrep GitHub Action
        id: trigger-scan
        uses: vulteria/vulrep-cli@v0.5.0
        with:
          project_code: 20nuZRTEOF
          token: ${{ secrets.VULREP_TOKEN }}
        
